export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_PENDING = "LOGIN_PENDING";
export const LEAVE_BALANCE_PENDING = "LEAVE_BALANCE_PENDING";
export const LEAVE_BALANCE_SUCCESS = "LEAVE_BALANCE_SUCCESS";
export const LEAVE_BALANCE_FAILED = "LEAVE_BALANCE_PENDING";
